language: go
sudo: false
go:
  - 1.10.2
  - 1.11
  - tip

script:
- go get ./...
- go get github.com/stretchr/testify/assert
- go get golang.org/x/lint/golint
- go vet ./...
- golint ./...
- go test ./...